--------------------------------------------------------
--  File created - Saturday-May-02-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMIN
--------------------------------------------------------

   CREATE SEQUENCE  "C##KLINIK_ADMIN"."SEQ_ADMIN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REKAM_MEDIS
--------------------------------------------------------

   CREATE SEQUENCE  "C##KLINIK_ADMIN"."SEQ_REKAM_MEDIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESEP
--------------------------------------------------------

   CREATE SEQUENCE  "C##KLINIK_ADMIN"."SEQ_RESEP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."ADMIN" 
   (	"ID_ADMIN" NUMBER, 
	"NAMA_ADMIN" VARCHAR2(100 BYTE), 
	"EMAIL_ADMIN" VARCHAR2(100 BYTE), 
	"PASSWORD_ADMIN" VARCHAR2(255 BYTE), 
	"NO_TELP_ADMIN" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APPOINTMENT
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."APPOINTMENT" 
   (	"APPOINTMENT_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PASIEN_ID" NUMBER(10,0), 
	"DOKTER_ID" NUMBER(10,0), 
	"TGL_APPOINTMENT" DATE, 
	"JAM_APPOINTMENT" VARCHAR2(5 BYTE), 
	"NOMOR_ANTRIAN" NUMBER(4,0), 
	"KELUHAN_AWAL" VARCHAR2(500 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'MENUNGGU', 
	"CATATAN" VARCHAR2(255 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOKTER
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."DOKTER" 
   (	"DOKTER_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAMA_DOKTER" VARCHAR2(100 BYTE), 
	"SPESIALISASI" VARCHAR2(100 BYTE), 
	"NO_SIP" VARCHAR2(30 BYTE), 
	"NO_TELEPON" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"JADWAL_PRAKTIK" VARCHAR2(200 BYTE), 
	"BIAYA_KONSULTASI" NUMBER(12,2), 
	"STATUS_AKTIF" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"EMAIL_DOKTER" VARCHAR2(100 BYTE), 
	"PASSWORD_DOKTER" VARCHAR2(255 BYTE), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBAT
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."OBAT" 
   (	"OBAT_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAMA_OBAT" VARCHAR2(100 BYTE), 
	"KATEGORI" VARCHAR2(50 BYTE), 
	"SATUAN" VARCHAR2(20 BYTE), 
	"STOK_TERSEDIA" NUMBER(8,0) DEFAULT 0, 
	"HARGA_SATUAN" NUMBER(12,2), 
	"TGL_KADALUARSA" DATE, 
	"DESKRIPSI" VARCHAR2(255 BYTE), 
	"STATUS_AKTIF" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PASIEN
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."PASIEN" 
   (	"PASIEN_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NIK" VARCHAR2(16 BYTE), 
	"NAMA_LENGKAP" VARCHAR2(100 BYTE), 
	"TANGGAL_LAHIR" DATE, 
	"JENIS_KELAMIN" CHAR(1 BYTE), 
	"ALAMAT" VARCHAR2(255 BYTE), 
	"NO_TELEPON" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"GOLONGAN_DARAH" VARCHAR2(3 BYTE), 
	"STATUS_AKTIF" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6), 
	"NAMA_PASIEN" VARCHAR2(100 BYTE), 
	"EMAIL_PASIEN" VARCHAR2(100 BYTE), 
	"PASSWORD_PASIEN" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REKAM_MEDIS
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" 
   (	"REKAM_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"APPOINTMENT_ID" NUMBER(10,0), 
	"DOKTER_ID" NUMBER(10,0), 
	"TGL_PERIKSA" DATE, 
	"KELUHAN" VARCHAR2(500 BYTE), 
	"DIAGNOSIS" VARCHAR2(500 BYTE), 
	"TINDAKAN" VARCHAR2(500 BYTE), 
	"TEKANAN_DARAH" VARCHAR2(10 BYTE), 
	"BERAT_BADAN" NUMBER(5,2), 
	"CATATAN_TAMBAHAN" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CATATAN_TAMBAHAN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table RESEP
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."RESEP" 
   (	"RESEP_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REKAM_ID" NUMBER(10,0), 
	"OBAT_ID" NUMBER(10,0), 
	"DOSIS" VARCHAR2(50 BYTE), 
	"ATURAN_PAKAI" VARCHAR2(100 BYTE), 
	"JUMLAH" NUMBER(6,0), 
	"CATATAN_RESEP" VARCHAR2(255 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"NAMA_OBAT_MANUAL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAGIHAN
--------------------------------------------------------

  CREATE TABLE "C##KLINIK_ADMIN"."TAGIHAN" 
   (	"TAGIHAN_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PASIEN_ID" NUMBER(10,0), 
	"APPOINTMENT_ID" NUMBER(10,0), 
	"TGL_TAGIHAN" DATE, 
	"BIAYA_KONSULTASI" NUMBER(12,2) DEFAULT 0, 
	"BIAYA_OBAT" NUMBER(12,2) DEFAULT 0, 
	"TOTAL_BIAYA" NUMBER(12,2), 
	"METODE_BAYAR" VARCHAR2(20 BYTE), 
	"STATUS_BAYAR" VARCHAR2(20 BYTE) DEFAULT 'BELUM'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View V_APPOINTMENT_LENGKAP
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##KLINIK_ADMIN"."V_APPOINTMENT_LENGKAP" ("APPOINTMENT_ID", "TGL_APPOINTMENT", "JAM_APPOINTMENT", "NOMOR_ANTRIAN", "PASIEN", "TELP_PASIEN", "DOKTER", "SPESIALISASI", "KELUHAN_AWAL", "STATUS") AS 
  SELECT A.APPOINTMENT_ID, A.TGL_APPOINTMENT, A.JAM_APPOINTMENT,
    A.NOMOR_ANTRIAN, P.NAMA_LENGKAP AS PASIEN,
    P.NO_TELEPON AS TELP_PASIEN, D.NAMA_DOKTER AS DOKTER,
    D.SPESIALISASI, A.KELUHAN_AWAL, A.STATUS
FROM APPOINTMENT A
JOIN PASIEN P ON A.PASIEN_ID = P.PASIEN_ID
JOIN DOKTER D ON A.DOKTER_ID = D.DOKTER_ID
;
--------------------------------------------------------
--  DDL for View V_REKAM_DAN_RESEP
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##KLINIK_ADMIN"."V_REKAM_DAN_RESEP" ("REKAM_ID", "TGL_PERIKSA", "PASIEN", "DOKTER", "DIAGNOSIS", "NAMA_OBAT", "DOSIS", "ATURAN_PAKAI", "JUMLAH", "SUBTOTAL_RESEP") AS 
  SELECT RM.REKAM_ID, RM.TGL_PERIKSA, P.NAMA_LENGKAP AS PASIEN,
    D.NAMA_DOKTER AS DOKTER, RM.DIAGNOSIS, O.NAMA_OBAT,
    R.DOSIS, R.ATURAN_PAKAI, R.JUMLAH,
    (O.HARGA_SATUAN * R.JUMLAH) AS SUBTOTAL_RESEP
FROM REKAM_MEDIS RM
JOIN APPOINTMENT A ON RM.APPOINTMENT_ID = A.APPOINTMENT_ID
JOIN PASIEN P ON A.PASIEN_ID = P.PASIEN_ID
JOIN DOKTER D ON RM.DOKTER_ID = D.DOKTER_ID
LEFT JOIN RESEP R ON RM.REKAM_ID = R.REKAM_ID
LEFT JOIN OBAT O ON R.OBAT_ID = O.OBAT_ID
;
--------------------------------------------------------
--  DDL for View V_TAGIHAN_PASIEN
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "C##KLINIK_ADMIN"."V_TAGIHAN_PASIEN" ("TAGIHAN_ID", "PASIEN", "TGL_TAGIHAN", "KONSULTASI", "OBAT", "TOTAL", "METODE_BAYAR", "STATUS_BAYAR") AS 
  SELECT T.TAGIHAN_ID, P.NAMA_LENGKAP AS PASIEN,
    TO_CHAR(T.TGL_TAGIHAN, 'DD/MM/YYYY') AS TGL_TAGIHAN,
    TO_CHAR(T.BIAYA_KONSULTASI, 'Rp FM999,999,999') AS KONSULTASI,
    TO_CHAR(T.BIAYA_OBAt, 'Rp FM999,999,999') AS OBAT,
    TO_CHAR(T.TOTAL_BIAYA, 'Rp FM999,999,999') AS TOTAL,
    NVL(T.METODE_BAYAR, '-') AS METODE_BAYAR, T.STATUS_BAYAR
FROM TAGIHAN T
JOIN PASIEN P ON T.PASIEN_ID = P.PASIEN_ID
;
REM INSERTING into C##KLINIK_ADMIN.ADMIN
SET DEFINE OFF;
Insert into C##KLINIK_ADMIN.ADMIN (ID_ADMIN,NAMA_ADMIN,EMAIL_ADMIN,PASSWORD_ADMIN,NO_TELP_ADMIN,CREATED_AT,UPDATED_AT) values ('1','Admin Klinik','admin@klinik.com','password123','021-1234567',to_date('25-04-2026','DD-MM-RRRR'),to_date('25-04-2026','DD-MM-RRRR'));
REM INSERTING into C##KLINIK_ADMIN.APPOINTMENT
SET DEFINE OFF;
Insert into C##KLINIK_ADMIN.APPOINTMENT (APPOINTMENT_ID,PASIEN_ID,DOKTER_ID,TGL_APPOINTMENT,JAM_APPOINTMENT,NOMOR_ANTRIAN,KELUHAN_AWAL,STATUS,CATATAN,CREATED_AT) values ('1','1','1',to_date('27-04-2026','DD-MM-RRRR'),'09:00','1','demam','MENUNGGU',null,to_timestamp('26-04-2026 15.14.42,507000000','DD-MM-RRRR HH24.MI.SSXFF'));
Insert into C##KLINIK_ADMIN.APPOINTMENT (APPOINTMENT_ID,PASIEN_ID,DOKTER_ID,TGL_APPOINTMENT,JAM_APPOINTMENT,NOMOR_ANTRIAN,KELUHAN_AWAL,STATUS,CATATAN,CREATED_AT) values ('2','1','1',to_date('28-04-2026','DD-MM-RRRR'),'09:00','1','demam','MENUNGGU',null,to_timestamp('26-04-2026 18.24.32,818000000','DD-MM-RRRR HH24.MI.SSXFF'));
REM INSERTING into C##KLINIK_ADMIN.DOKTER
SET DEFINE OFF;
Insert into C##KLINIK_ADMIN.DOKTER (DOKTER_ID,NAMA_DOKTER,SPESIALISASI,NO_SIP,NO_TELEPON,EMAIL,JADWAL_PRAKTIK,BIAYA_KONSULTASI,STATUS_AKTIF,CREATED_AT,EMAIL_DOKTER,PASSWORD_DOKTER,IS_ACTIVE) values ('1','Dr. Budi Santoso','Sp.PD','SIP001','08111111111','dr.budi@klinik.com',null,'100000','1',to_timestamp('25-04-2026 10.15.19,710000000','DD-MM-RRRR HH24.MI.SSXFF'),'dr.budi@klinik.com','password123','1');
REM INSERTING into C##KLINIK_ADMIN.OBAT
SET DEFINE OFF;
REM INSERTING into C##KLINIK_ADMIN.PASIEN
SET DEFINE OFF;
Insert into C##KLINIK_ADMIN.PASIEN (PASIEN_ID,NIK,NAMA_LENGKAP,TANGGAL_LAHIR,JENIS_KELAMIN,ALAMAT,NO_TELEPON,EMAIL,GOLONGAN_DARAH,STATUS_AKTIF,CREATED_AT,UPDATED_AT,NAMA_PASIEN,EMAIL_PASIEN,PASSWORD_PASIEN) values ('1','3201010101010001','Andi Firmansyah',to_date('25-04-2026','DD-MM-RRRR'),'L','lamongan','08123456789','andi@email.com',null,'Y',to_timestamp('25-04-2026 10.15.19,692000000','DD-MM-RRRR HH24.MI.SSXFF'),to_timestamp('26-04-2026 15.16.31,204000000','DD-MM-RRRR HH24.MI.SSXFF'),'Andi Firmansyah','andi@email.com','password123');
REM INSERTING into C##KLINIK_ADMIN.REKAM_MEDIS
SET DEFINE OFF;
REM INSERTING into C##KLINIK_ADMIN.RESEP
SET DEFINE OFF;
REM INSERTING into C##KLINIK_ADMIN.TAGIHAN
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IDX_OBAT_KATEG
--------------------------------------------------------

  CREATE INDEX "C##KLINIK_ADMIN"."IDX_OBAT_KATEG" ON "C##KLINIK_ADMIN"."OBAT" ("KATEGORI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_TAG_STATUS
--------------------------------------------------------

  CREATE INDEX "C##KLINIK_ADMIN"."IDX_TAG_STATUS" ON "C##KLINIK_ADMIN"."TAGIHAN" ("STATUS_BAYAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_RESEP_REKAM
--------------------------------------------------------

  CREATE INDEX "C##KLINIK_ADMIN"."IDX_RESEP_REKAM" ON "C##KLINIK_ADMIN"."RESEP" ("REKAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PASIEN_NAMA
--------------------------------------------------------

  CREATE INDEX "C##KLINIK_ADMIN"."IDX_PASIEN_NAMA" ON "C##KLINIK_ADMIN"."PASIEN" ("NAMA_LENGKAP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APPT_PASIEN
--------------------------------------------------------

  CREATE INDEX "C##KLINIK_ADMIN"."IDX_APPT_PASIEN" ON "C##KLINIK_ADMIN"."APPOINTMENT" ("PASIEN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APPT_TGL
--------------------------------------------------------

  CREATE INDEX "C##KLINIK_ADMIN"."IDX_APPT_TGL" ON "C##KLINIK_ADMIN"."APPOINTMENT" ("TGL_APPOINTMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_APPT_STATUS
--------------------------------------------------------

  CREATE INDEX "C##KLINIK_ADMIN"."IDX_APPT_STATUS" ON "C##KLINIK_ADMIN"."APPOINTMENT" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TAGIHAN
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("TAGIHAN_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("PASIEN_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("APPOINTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("TGL_TAGIHAN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("BIAYA_KONSULTASI" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("BIAYA_OBAT" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("TOTAL_BIAYA" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" MODIFY ("STATUS_BAYAR" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" ADD CHECK (STATUS_BAYAR IN ('BELUM','LUNAS','CICIL')) ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" ADD PRIMARY KEY ("TAGIHAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" ADD UNIQUE ("APPOINTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOKTER
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" MODIFY ("DOKTER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" MODIFY ("NAMA_DOKTER" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" MODIFY ("SPESIALISASI" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" MODIFY ("NO_SIP" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" MODIFY ("NO_TELEPON" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" MODIFY ("BIAYA_KONSULTASI" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" MODIFY ("STATUS_AKTIF" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" ADD PRIMARY KEY ("DOKTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" ADD UNIQUE ("NO_SIP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."DOKTER" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASIEN
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" MODIFY ("PASIEN_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" MODIFY ("NIK" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" MODIFY ("NAMA_LENGKAP" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" MODIFY ("TANGGAL_LAHIR" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" MODIFY ("JENIS_KELAMIN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" MODIFY ("NO_TELEPON" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" MODIFY ("STATUS_AKTIF" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" ADD CHECK (JENIS_KELAMIN IN ('L','P')) ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" ADD PRIMARY KEY ("PASIEN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" ADD UNIQUE ("NIK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."PASIEN" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REKAM_MEDIS
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" MODIFY ("REKAM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" MODIFY ("APPOINTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" MODIFY ("DOKTER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" MODIFY ("TGL_PERIKSA" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" MODIFY ("KELUHAN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" MODIFY ("DIAGNOSIS" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" ADD PRIMARY KEY ("REKAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" ADD UNIQUE ("APPOINTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBAT
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" MODIFY ("OBAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" MODIFY ("NAMA_OBAT" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" MODIFY ("KATEGORI" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" MODIFY ("SATUAN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" MODIFY ("STOK_TERSEDIA" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" MODIFY ("HARGA_SATUAN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" MODIFY ("STATUS_AKTIF" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."OBAT" ADD PRIMARY KEY ("OBAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPOINTMENT
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" MODIFY ("APPOINTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" MODIFY ("PASIEN_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" MODIFY ("DOKTER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" MODIFY ("TGL_APPOINTMENT" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" MODIFY ("JAM_APPOINTMENT" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" MODIFY ("NOMOR_ANTRIAN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" ADD CHECK (STATUS IN ('MENUNGGU','SELESAI','BATAL')) ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" ADD PRIMARY KEY ("APPOINTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."ADMIN" MODIFY ("NAMA_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."ADMIN" MODIFY ("EMAIL_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."ADMIN" MODIFY ("PASSWORD_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."ADMIN" ADD PRIMARY KEY ("ID_ADMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."ADMIN" ADD UNIQUE ("EMAIL_ADMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESEP
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."RESEP" MODIFY ("RESEP_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."RESEP" MODIFY ("REKAM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KLINIK_ADMIN"."RESEP" ADD PRIMARY KEY ("RESEP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPOINTMENT
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" ADD CONSTRAINT "FK_APPT_PASIEN" FOREIGN KEY ("PASIEN_ID")
	  REFERENCES "C##KLINIK_ADMIN"."PASIEN" ("PASIEN_ID") ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."APPOINTMENT" ADD CONSTRAINT "FK_APPT_DOKTER" FOREIGN KEY ("DOKTER_ID")
	  REFERENCES "C##KLINIK_ADMIN"."DOKTER" ("DOKTER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REKAM_MEDIS
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" ADD CONSTRAINT "FK_RM_APPT" FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "C##KLINIK_ADMIN"."APPOINTMENT" ("APPOINTMENT_ID") ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."REKAM_MEDIS" ADD CONSTRAINT "FK_RM_DOKTER" FOREIGN KEY ("DOKTER_ID")
	  REFERENCES "C##KLINIK_ADMIN"."DOKTER" ("DOKTER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESEP
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."RESEP" ADD CONSTRAINT "FK_RESEP_RM" FOREIGN KEY ("REKAM_ID")
	  REFERENCES "C##KLINIK_ADMIN"."REKAM_MEDIS" ("REKAM_ID") ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."RESEP" ADD CONSTRAINT "FK_RESEP_OBAT" FOREIGN KEY ("OBAT_ID")
	  REFERENCES "C##KLINIK_ADMIN"."OBAT" ("OBAT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAGIHAN
--------------------------------------------------------

  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" ADD CONSTRAINT "FK_TAG_PASIEN" FOREIGN KEY ("PASIEN_ID")
	  REFERENCES "C##KLINIK_ADMIN"."PASIEN" ("PASIEN_ID") ENABLE;
  ALTER TABLE "C##KLINIK_ADMIN"."TAGIHAN" ADD CONSTRAINT "FK_TAG_APPT" FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "C##KLINIK_ADMIN"."APPOINTMENT" ("APPOINTMENT_ID") ENABLE;
